### ISSUE TITLE
How do I exclude a line from being formatted?

### ISSUE THREAD

**Issue by aishwaryaanegundi** [CyberShadow/squelch#3]
squelch formats the sql query as below:

from
wide_number_mode=>'round')))
to
wide_number_mode = > 'round')))

which is creating issue

**Comment by CyberShadow** [comment]
Hi, what is this syntax? I don't see it on https://cloud.google.com/bigquery/docs/reference/standard-sql/operators

**Comment by aishwaryaanegundi** [comment]
> Hi, what is this syntax? I don't see it on https://cloud.google.com/bigquery/docs/reference/standard-sql/operators

It is found in the big query parse json expression: https://cloud.google.com/bigquery/docs/reference/standard-sql/json_functions#parse_json

May be we can just add this operator (=>) to the list of allowed operators.

**Comment by CyberShadow** [comment]
Thanks! I see, it's some kind of syntax for named arguments.

I tagged v0.2.5 with a fix, that should fix the problem on your side once you bump the version.

**Comment by aishwaryaanegundi** [comment]
Thank you for the quick fix. It works now!
